### PR TITLE
Update issuance rate on config files

### PR DESCRIPTION
**Pull request by tmigone**
Update to match the post merge values.

### CODE REVIEW

**Review by pcarranzav — APPROVED** [review]
LGTM

**Review by abarmat — DISMISSED** [review]
Looks good

**Comment by tmigone** [comment]
CI test failed due to known bug here: https://github.com/graphprotocol/contracts/issues/576

**Review by pcarranzav — APPROVED** [review]

**Comment by MarekSykokora** [comment]
Hello, I receive messages from you and you use the wrong email if there was
any communication, it was a scam, correct communication, no it's a lot of
messages and I don't look into it to make everything okay, please contact
MarekSyk, this address is no longer used to which you write and please help
with my contract, I'm completely unhappy that I can't move with it, thank
you very much Marek

pá 25. 11. 2022 v 19:59 odesílatel Tomás Migone ***@***.***>
napsal:

**Pull request merged**
